/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 24.2 and Signal Processing Toolbox 24.2.
 * Generated on: 30-Nov-2025 00:35:08
 */

/*
 * 离散时间 IIR 滤波器(实数)
 * ----------------
 * 滤波器结构  : 直接 II 型
 * 分子 长度  : 3
 * 分母 长度  : 3
 * 稳定     : 是
 * 线性相位   : 否
 */

/* General type conversion for MATLAB generated C-code  */
/* 
 * Expected path to tmwtypes.h 
 * D:\Tools\MATLAB\R2024b\extern\include\tmwtypes.h 
 */
const int RESP_100Hz_NL = 3;
const double RESP_100Hz_NUM[3] = {
     0.9396002918425,   -0.580704916198,   0.9396002918425
};
const int RESP_100Hz_DL = 3;
const double RESP_100Hz_DEN[3] = {
                   1,   -0.580704916198,    0.879200583685
};
