/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 24.2 and Signal Processing Toolbox 24.2.
 * Generated on: 29-Nov-2025 23:32:07
 */

/*
 * 离散时间 IIR 滤波器(实数)
 * ----------------
 * 滤波器结构  : 直接 II 型
 * 分子 长度  : 3
 * 分母 长度  : 3
 * 稳定     : 是
 * 线性相位   : 否
 */

/* General type conversion for MATLAB generated C-code  */
/* 
 * Expected path to tmwtypes.h 
 * D:\Tools\MATLAB\R2024b\extern\include\tmwtypes.h 
 */
const int RESP_50Hz_NL = 3;
const double RESP_50Hz_NUM[3] = {
     0.9115207056625,   -1.474871483211,   0.9115207056625
};
const int RESP_50Hz_DL = 3;
const double RESP_50Hz_DEN[3] = {
                   1,   -1.474871483211,   0.8230414113249
};
