/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 24.2 and Signal Processing Toolbox 24.2.
 * Generated on: 30-Nov-2025 00:42:30
 */

/*
 * 离散时间 IIR 滤波器(实数)
 * ----------------
 * 滤波器结构  : 直接 II 型，二阶节
 * 节数     : 1
 * 稳定     : 是
 * 线性相位   : 否
 */

/* General type conversion for MATLAB generated C-code  */
/* 
 * Expected path to tmwtypes.h 
 * D:\Tools\MATLAB\R2024b\extern\include\tmwtypes.h 
 */
#define MWSPT_NSEC 3
const int RESP_Lower_NL[MWSPT_NSEC] = { 1,3,1 };
const double RESP_Lower_NUM[MWSPT_NSEC][3] = {
  {
     0.1075169803738,                 0,                 0 
  },
  {
                   1,                 2,                 1 
  },
  {
     0.8912509381337,                 0,                 0 
  }
};
const int RESP_Lower_DL[MWSPT_NSEC] = { 1,3,1 };
const double RESP_Lower_DEN[MWSPT_NSEC][3] = {
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.029171022077,   0.4592389435724 
  },
  {
                   1,                 0,                 0 
  }
};
